---
# RHEL 8 must be a vendor-supported release.
manage_230221: false
# Administrative

# All RHEL 8 local disk partitions must implement cryptographic mechanisms to prevent unauthorized disclosure or modification of all information that requires at rest protection.
manage_230224: false
# Not particularly easy to automate the check, and definitely not to remediate



...