---
- name: Remove Cockpit message
  ansible.builtin.file:
    path: /etc/issue.d/cockpit.issue
    state: absent

- name: Allow iptables to see bridged network traffic
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
...